-- =====================================================================
-- MIGRACIÓN 001 :: Esquema de tablas del foro 
-- Base de datos: Oracle Autonomous DB
-- Ejecutar con: npm run db:migrate
-- =====================================================================

-- Usuarios sincronizados con la Intranet (no hay login/registro propio)
CREATE TABLE users (
  id                   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_intranet_id VARCHAR2(100)  NOT NULL,
  full_name            VARCHAR2(200)  NOT NULL,
  role_title           VARCHAR2(150),
  avatar_initials      VARCHAR2(10),
  reputation_points    NUMBER DEFAULT 0,
  created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR2(100) NOT NULL,
  slug        VARCHAR2(100) NOT NULL,
  description VARCHAR2(500),
  color_code  VARCHAR2(20)
);

CREATE TABLE questions (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     NUMBER NOT NULL,
  category_id NUMBER NOT NULL,
  title       VARCHAR2(300) NOT NULL,
  body_text   CLOB NOT NULL,
  status      VARCHAR2(20) DEFAULT 'open',
  votes_count NUMBER DEFAULT 0,
  views_count NUMBER DEFAULT 0,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_questions_user_cat FOREIGN KEY (category_id) REFERENCES categories(id),
  CONSTRAINT fk_questions_user      FOREIGN KEY (user_id)     REFERENCES users(id),
  CONSTRAINT ck_questions_status    CHECK (status IN ('open', 'in_progress', 'resolved'))
);

CREATE TABLE question_tags (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id NUMBER NOT NULL,
  tag_name    VARCHAR2(100) NOT NULL,
  CONSTRAINT fk_question_tags_question FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE answers (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id      NUMBER NOT NULL,
  user_id          NUMBER NOT NULL,
  body_text        CLOB NOT NULL,
  is_accepted      NUMBER(1) DEFAULT 0,
  parent_answer_id NUMBER,
  votes_count      NUMBER DEFAULT 0,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_answers_question FOREIGN KEY (question_id)      REFERENCES questions(id) ON DELETE CASCADE,
  CONSTRAINT fk_answers_user     FOREIGN KEY (user_id)          REFERENCES users(id),
  CONSTRAINT fk_answers_parent   FOREIGN KEY (parent_answer_id) REFERENCES answers(id)
);

CREATE TABLE saved_items (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    NUMBER NOT NULL,
  item_type  VARCHAR2(20) NOT NULL,
  item_id    NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_saved_items_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE projects (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      NUMBER NOT NULL,
  category_id  NUMBER,
  title        VARCHAR2(300) NOT NULL,
  description  CLOB,
  repo_url     VARCHAR2(500),
  status_badge VARCHAR2(50),
  stars_count  NUMBER DEFAULT 0,
  forks_count  NUMBER DEFAULT 0,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_projects_user     FOREIGN KEY (user_id)     REFERENCES users(id),
  CONSTRAINT fk_projects_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE project_stack (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id NUMBER NOT NULL,
  technology VARCHAR2(100) NOT NULL,
  CONSTRAINT fk_project_stack_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE attachments (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attachable_type VARCHAR2(30)  NOT NULL,
  attachable_id   NUMBER        NOT NULL,
  file_name       VARCHAR2(255) NOT NULL,
  file_url        VARCHAR2(500) NOT NULL,
  file_size       NUMBER DEFAULT 0,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para acelerar las consultas más comunes del feed.
CREATE INDEX idx_questions_category  ON questions(category_id);
CREATE INDEX idx_questions_user      ON questions(user_id);
CREATE INDEX idx_questions_status    ON questions(status);
CREATE INDEX idx_answers_question    ON answers(question_id);
CREATE INDEX idx_question_tags_q     ON question_tags(question_id);
CREATE INDEX idx_saved_items_user    ON saved_items(user_id);